name: notevault

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:17-alpine
    container_name: notevault-postgres
    environment:
      POSTGRES_DB: notevault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notevault-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO S3 存储
  minio:
    image: minio/minio:latest
    container_name: notevault-minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - notevault-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # NATS 消息队列
  nats:
    image: nats:2.8.2-alpine3.15
    container_name: notevault-nats
    ports:
      - "4222:4222"   # 客户端连接端口
      - "8222:8222"   # HTTP 监控端口
      - "8223:8223"   # HTTPS 监控端口
      - "9090:9090"   # Prometheus 指标端口
    volumes:
      - nats_data:/data
      - ./configs/nats.conf:/etc/nats/nats-server.conf
    command: ["-c", "/etc/nats/nats-server.conf"]
    networks:
      - notevault-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8222/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Prometheus 监控
  prometheus:
    image: prom/prometheus:latest
    container_name: notevault-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    networks:
      - notevault-network

  # 可选：Grafana 用于可视化监控数据
  grafana:
    image: grafana/grafana:latest
    container_name: notevault-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - notevault-network
    depends_on:
      - prometheus

volumes:
  postgres_data:
  minio_data:
  nats_data:
  prometheus_data:
  grafana_data:

networks:
  notevault-network:
    driver: bridge
