version: 3

tasks:
  default:
    cmds:
      - task: build
    desc: default task

  build:
    cmds:
      - go build ./cmd/notevault
    desc: Build the Go application

  build:release:
    cmds:
      - go build -ldflags="-s -w" -o ./bin/notevault{{ exeExt }} ./cmd/notevault
    desc: Build the Go application for release

  lint:
    cmds:
      - golangci-lint run --fix
    desc: Run lint with golangci-lint

  fmt:
    cmds:
      - golangci-lint fmt .
    desc: Format Go code with golangci-lint

  init:
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.3.1
      - go mod tidy
    desc: Initialize Go module and Install necessary tools
