version: 3

tasks:
  default:
    cmds:
      - task: build
    desc: default task

  build:
    cmds:
      - go build ./cmd/notevault
    desc: Build the Go application

  build:release:
    cmds:
      - go build -ldflags="-s -w" -o ./bin/notevault{{ exeExt }} ./cmd/notevault
    desc: Build the Go application for release
