version: 3

tasks:
  default:
    cmds:
      - task: build
    desc: default task

  build:
    cmds:
      - go build ./cmd/notevault
    desc: Build the Go application

  build:release:
    cmds:
      - go build -ldflags="-s -w" -o ./bin/notevault{{ exeExt }} ./cmd/notevault
    desc: Build the Go application for release

  lint:
    cmds:
      - golangci-lint run --fix
    desc: Run lint with golangci-lint
    silent: true

  fmt:
    cmds:
      - golangci-lint fmt .
    desc: Format Go code with golangci-lint
    silent: true

  init:
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.3.1
      - go install github.com/swaggo/swag/cmd/swag@latest
      - go mod tidy
    desc: Initialize Go module and Install necessary tools

  dev:
    cmds:
      - go run ./cmd/notevault
    desc: Build and run the application for development
    watch: true
    sources:
      - ./**/*.go

  docs:
    cmds:
      - swag init -g ./cmd/notevault/main.go -o ./docs
    desc: Generate Swagger API documentation
