@fileurl=http://localhost:8080/api/v1/files

### 生成预签名 URL JSON

POST {{fileurl}}/upload/urls/policy
Content-Type: application/json

{
  "files": [
    {
      "file_name": "example1.txt",
      "file_type": "text/plain"
    },
    {
      "file_name": "example2.jpg",
      "file_type": "image/jpeg"
    }
  ]
}

### 生成预签名 URL YAML

POST {{fileurl}}/upload/urls/policy
Content-Type: application/yaml

files:
  - file_name: example1.txt
    file_type: text/plain
  - file_name: example2.jpg
    file_type: image/jpeg

### 获取文件访问 URL JSON

POST {{fileurl}}/download/url
Content-Type: application/json

{
  "files": [
    {
      "object_key": "user/2023/10/uuid_example1.txt"
    },
    {
      "object_key": "user/2023/10/uuid_example2.jpg"
    }
  ]
}
