global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "notevault"
    static_configs:
      - targets: ["notevault-app:9090"]
    scrape_interval: 5s

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:9187"]
    scrape_interval: 10s

  - job_name: "nats"
    static_configs:
      - targets: ["nats:8222"]
    scrape_interval: 10s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
