// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q           = new(Query)
	File        *file
	FileTag     *fileTag
	FileVersion *fileVersion
	Tag         *tag
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	File = &Q.File
	FileTag = &Q.FileTag
	FileVersion = &Q.FileVersion
	Tag = &Q.Tag
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:          db,
		File:        newFile(db, opts...),
		FileTag:     newFileTag(db, opts...),
		FileVersion: newFileVersion(db, opts...),
		Tag:         newTag(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	File        file
	FileTag     fileTag
	FileVersion fileVersion
	Tag         tag
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		File:        q.File.clone(db),
		FileTag:     q.FileTag.clone(db),
		FileVersion: q.FileVersion.clone(db),
		Tag:         q.Tag.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		File:        q.File.replaceDB(db),
		FileTag:     q.FileTag.replaceDB(db),
		FileVersion: q.FileVersion.replaceDB(db),
		Tag:         q.Tag.replaceDB(db),
	}
}

type queryCtx struct {
	File        IFileDo
	FileTag     IFileTagDo
	FileVersion IFileVersionDo
	Tag         ITagDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		File:        q.File.WithContext(ctx),
		FileTag:     q.FileTag.WithContext(ctx),
		FileVersion: q.FileVersion.WithContext(ctx),
		Tag:         q.Tag.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
