# only for development, don't use in production
name: notevault-dev

x-env: &x-env
  POSTGRES_USER: notevault
  POSTGRES_PASSWORD: notevault
  POSTGRES_DB: notevault

services:
  postgres:
    image: postgres:17-alpine
    container_name: notevault-postgres
    environment: *x-env
    ports:
      - "5432:5432"
    volumes:
      - notevault_db:/var/lib/postgresql/data
      - ../../sql/schema/001-file.sql:/docker-entrypoint-initdb.d/init.sql

  minio:
    image: minio/minio:latest
    container_name: notevault-minio
    environment:
      MINIO_ROOT_USER: notevault
      MINIO_ROOT_PASSWORD: notevault
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Web UI port
    volumes:
      - notevault_minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nats:
    image: nats:2.8.2-alpine3.15
    container_name: notevault-nats-1
    ports:
      - "4222:4222" # Client port
      - "8222:8222" # HTTP port
      - "6222:6222" # Cluster port
    command: >
      --server_name nats-1 
      --cluster_name NATS 
      --cluster nats://0.0.0.0:6222 
      --routes=nats://nats1:6222
      --http_port 8222
      --user notevault_nats
      --pass notevault_nats
      --jetstream
    volumes:
      - notevault_nats_1:/data
    networks:
      - nats_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  notevault_db:
  notevault_minio:
  notevault_nats_1:

networks:
  nats_network:
    name: nats
