# NoteVault 应用程序配置示例
# 支持格式: yaml, json, toml, dotenv

# 服务器配置
server:
  port: 8080
  host: "0.0.0.0"
  log_level: "info"
  reload_config: true
  debug: true
  timeout: 30
  read_timeout: 10
  write_timeout: 10

# 数据库配置
db:
  type: "postgresql"
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  database: "notevault"
  sslmode: "disable"
  max_open_conns: 0
  max_idle_conns: 5
  enable_metrics: true

# S3 存储配置
s3:
  endpoint: "localhost:9000"
  access_key_id: "minioadmin"
  secret_access_key: "minioadmin"
  use_ssl: false
  bucket_name:
    - "notevault"
  region: "us-east-1"

# 消息队列配置
mq:
  type: "nats"  # 支持: nats, redis
  common:
    url: "localhost:4222"
    user: ""
    password: ""
    cluster_id: "notevault-cluster"
    client_id: "notevault-app"
    max_reconnects: 5
    reconnect_wait: 5
    enable_metrics: true
    endpoint: ":9092"
  # Redis 配置（当 type 为 redis 时使用）
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0

# 日志配置
log:
  enable_file: true
  file_path: "logs/notevault.log"
  max_size_mb: 100
  max_backups: 7
  max_age_days: 28
  compress: true
  level: "info"

# 分布式追踪配置
tracing:
  enabled: false
  service_name: "notevault"
  service_version: "1.0.0"
  exporter_type: "otlp-http"
  endpoint: "http://localhost:4318"
  sample_rate: 1.0
  batch_timeout: "5s"
  max_batch_size: 512
  max_queue_size: 2048

# 监控指标配置
metrics:
  enabled: false
  service_name: "notevault"
  service_version: "1.0.0"
  exporter_type: "prometheus"
  endpoint: ":9091"
  collect_interval: "15s"
  runtime_metrics: true
  custom_metrics: []
  labels:
    service: "notevault"
    version: "1.0.0"
  pprof: true

# 速率限制（可选）
rate_limit:
  enabled: true
  rps: 100
  burst: 200
  # global | ip | header:X-Forwarded-For | header:X-API-Key | header:Authorization
  key: "ip"

# 熔断器（可选）
circuit_breaker:
  enabled: true
  failure_rate: 0.5
  min_requests: 20
  interval_seconds: 60
  timeout_seconds: 30
  max_requests_in_half: 5

# 键值存储配置
kv:
  type: "memory"  # 支持: memory, redis, nats, groupcache
  # redis:
  #   addr: "localhost:6379"
  #   password: ""
  #   db: 0
  # nats:
  #   url: "localhost:4222"
  #   user: ""
  #   password: ""
  #   bucket: "notevault-kv"
  # groupcache:
  #   name: "notevault-cache"
  #   cache_bytes: 536870912  # 512MB
  #   peers: []
  #   self: "http://localhost:8080"
