// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFile = "files"

// File mapped from table <files>
type File struct {
	FileID         string `gorm:"column:file_id;primaryKey" json:"file_id"`
	UserID         string `gorm:"column:user_id;not null" json:"user_id"`
	FileName       string `gorm:"column:file_name;not null" json:"file_name"`
	FileType       string `gorm:"column:file_type;not null" json:"file_type"`
	ContentType    string `gorm:"column:content_type;not null" json:"content_type"`
	Size           int64  `gorm:"column:size;not null" json:"size"`
	Path           string `gorm:"column:path;not null" json:"path"`
	CreatedAt      int64  `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt      int64  `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt      int64  `gorm:"column:deleted_at" json:"deleted_at"`
	Status         int32  `gorm:"column:status;not null" json:"status"`
	TrashedAt      int64  `gorm:"column:trashed_at" json:"trashed_at"`
	CurrentVersion int32  `gorm:"column:current_version;not null;default:1" json:"current_version"`
	Description    string `gorm:"column:description" json:"description"`
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
