// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFileVersion = "file_versions"

// FileVersion mapped from table <file_versions>
type FileVersion struct {
	VersionID     string `gorm:"column:version_id;primaryKey" json:"version_id"`
	FileID        string `gorm:"column:file_id;not null" json:"file_id"`
	VersionNumber int32  `gorm:"column:version_number;not null" json:"version_number"`
	Size          int64  `gorm:"column:size;not null" json:"size"`
	Path          string `gorm:"column:path;not null" json:"path"`
	ContentType   string `gorm:"column:content_type;not null" json:"content_type"`
	CreatedAt     int64  `gorm:"column:created_at;not null" json:"created_at"`
	DeletedAt     int64  `gorm:"column:deleted_at" json:"deleted_at"`
	Status        int32  `gorm:"column:status;not null" json:"status"`
	CommitMessage string `gorm:"column:commit_message" json:"commit_message"`
}

// TableName FileVersion's table name
func (*FileVersion) TableName() string {
	return TableNameFileVersion
}
