// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFileTag = "file_tags"

// FileTag mapped from table <file_tags>
type FileTag struct {
	FileID string `gorm:"column:file_id;primaryKey" json:"file_id"`
	TagID  string `gorm:"column:tag_id;primaryKey" json:"tag_id"`
}

// TableName FileTag's table name
func (*FileTag) TableName() string {
	return TableNameFileTag
}
